apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 3.7.1
    chart: ingress-nginx
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
