apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  destination:
    namespace: keda
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 1.5.0
    chart: keda
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

