apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/novotnyjohn/prometheus-operator'
    path: .
    targetRevision: HEAD
    helm:
      valueFiles:
        - custom-values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

