apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roles
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/novotnyjohn/k8s-roles
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true

